### ISSUE TITLE
verbosity error

### ISSUE THREAD

**Issue by NabHamzah** [vanhuyz/CycleGAN-TensorFlow#110]
Hello... as I run the train.py I get a verbosity error. Can someone help me as I'm new with python and TensorFlow.

This is the error that I get when I run train.py: 

Traceback (most recent call last):
  File "train.py", line 149, in <module>
    app.run(train)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 293, in run
    flags_parser,
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 359, in _run_init
    logging.use_absl_handler()
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\absl\logging\__init__.py", line 1147, in use_absl_handler
    FLAGS['verbosity']._update_logging_levels()  # pylint: disable=protected-access
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\absl\flags\_flagvalues.py", line 463, in __getitem__
    return self._flags()[name]
KeyError: 'verbosity'

**Comment by Abhishek-Rnjn** [comment]
Were you able to solve it?

**Comment by beshining** [comment]
Have u modified the file "train.py"?  This file has a maximum line number 135, while your logo shows " File "train.py", line 149, in..."

**Comment by NabHamzah** [comment]
> 
> 
> Were you able to solve it?

nope

**Comment by ujwalakoriraj** [comment]
Has anyone got a solution for this problem? I am facing the same issue. Please help.

**Comment by AnishTatke** [comment]
Anyone able to solve it yet? Please help
