### ISSUE TITLE
Inference runs error

### ISSUE THREAD

**Issue by mamahhh** [vanhuyz/CycleGAN-TensorFlow#90]
When I run the inference.py following the Readme, there are some errors:
`Traceback (most recent call last):
  File "inference.py", line 49, in <module>
    tf.app.run()
  File "/home/masijia/.conda/envs/cycle/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "inference.py", line 46, in main
    inference()
  File "inference.py", line 26, in inference
    image_data = f.read()
  File "/home/masijia/.conda/envs/cycle/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 106, in read
    self._preread_check()
  File "/home/masijia/.conda/envs/cycle/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 73, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/masijia/.conda/envs/cycle/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/masijia/.conda/envs/cycle/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: input_sample.jpg`
What should I do to solve it?

**Comment by vanhuyz** [comment]
It said that `NotFoundError: input_sample.jpg`.
So you need to provide a input image with name `input_sample.jpg`. Of course, you can change the name as you want.
